### ISSUE TITLE
Catalog API

### ISSUE THREAD

**Issue by andrew-svirin** [killbill/killbill-client-php#9]
How to import (POST) catalog?

**Comment by pierre** [comment]
This is not yet supported: https://github.com/killbill/killbill-client-php/blob/26bb8e144d1e186b5ff3f163c303539c94a7c93e/lib/killbill/catalog.php.

Would you be interested in submitting a pull request? The API is documented here: http://killbill.io/api/#!/catalog/uploadCatalogXml.

**Comment by AndriySvirin** [comment]
Not sure that it possible in context of this library, because common format is JSON and catalog is in XML format.
Would be good to make PHP-generator for catalog with UI interpreted by form.

**Comment by pierre** [comment]
> Not sure that it possible in context of this library, because common format is JSON and catalog is in XML format.

The catalog is indeed in XML format but it shouldn't matter for the POST. Instead of [sending JSON](https://github.com/killbill/killbill-client-php/blob/26bb8e144d1e186b5ff3f163c303539c94a7c93e/lib/killbill/resource.php#L46), we simply need a different function to upload the data directly (maybe look-up the file via `realpath`).

> Would be good to make PHP-generator for catalog with UI interpreted by form.

Do you mean having a UI to generate the catalog? This is indeed in our roadmap. For now, clients just write it by hand and upload the file (e.g. in [ruby](https://github.com/killbill/killbill-client-ruby/blob/master/lib/killbill_client/models/catalog.rb#L43-L59)).

**Comment by adzadzadz** [comment]
There's a small issue with the catalog api with killbill v0.18.15.
https://github.com/killbill/killbill-client-php/blob/master/src/Catalog.php#L53
the full catalog returns as an array and within it the product objects. It then gives a PHP Notice "Trying to get property of non-object". 
Fix:
``
   public function getBaseProducts()
    {
        $baseProducts = array();
        foreach ($this->fullCatalog[0]->products as $product) {
            if ($product->type == 'BASE') {
                $baseProducts[] = $product;
            }
        }

        return $baseProducts;
    }

**Comment by pierre** [comment]
The client is now auto-generated.
